### ISSUE TITLE
Sijia's To-do for Thanksgiving week 

### ISSUE THREAD

**Issue by Konic-NLP** [jinzhao3611/umr-annotation-tool#6]
- [x] Double check whether the concept in the graph after lemmatization
- [x]  Automatic word segmentation of typing interface
- [x] Color for different token status 
- [x]  A initial version of query box

**Comment by Konic-NLP** [comment]
get_lemma need to decouple  from conceptdrop down, right now implement a initial version
